
options(warn = -1)
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(shinyjqui))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(httr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(shinyWidgets))
suppressPackageStartupMessages(library(bslib))
suppressPackageStartupMessages(library(shinythemes))
suppressPackageStartupMessages(library(shinycssloaders))
suppressPackageStartupMessages(library(bsicons))
suppressPackageStartupMessages(library(svglite))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ggtext))

#suppressPackageStartupMessages(library(readr))
#suppressPackageStartupMessages(library(ggsignif))
#suppressPackageStartupMessages(library(colourpicker))
#suppressPackageStartupMessages(library(ggrepel))
#suppressPackageStartupMessages(library(ggpubr))
#suppressPackageStartupMessages(library(reshape2))
#suppressPackageStartupMessages(library(rstatix))
#suppressPackageStartupMessages(library(survival))
#suppressPackageStartupMessages(library(survminer))
#suppressPackageStartupMessages(library(gtsummary))
#suppressPackageStartupMessages(library(powerSurvEpi))
#suppressPackageStartupMessages(library(readxl))
#suppressPackageStartupMessages(library(circlize))
#suppressPackageStartupMessages(library(listviewer))
#suppressPackageStartupMessages(library(readtext))
#suppressPackageStartupMessages(library(shinyalert))
#suppressPackageStartupMessages(library(magick))
#suppressPackageStartupMessages(library(lme4))
#suppressPackageStartupMessages(library(sass))
#suppressPackageStartupMessages(library(ggsankey))
#suppressPackageStartupMessages(library(ComplexHeatmap))
#suppressPackageStartupMessages(library(InteractiveComplexHeatmap))

